# Generated by Django 3.2.9 on 2021-11-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=60)),
                ('turi', models.CharField(choices=[('Y', 'Yuridikt'), ('J', 'Jismoniy')], max_length=50)),
                ('raqami', models.IntegerField(default=9989)),
                ('summa', models.IntegerField(default=0)),
                ('tashkilot', models.CharField(max_length=255)),
                ('holati', models.CharField(choices=[('Y', 'Yangi'), ('M', 'Moderatsiada'), ('T', 'Tasdiqlangan'), ('B', 'Bekor qilingan')], default='Yangi', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Homiylar',
            },
        ),
    ]
