# Generated by Django 3.2.9 on 2021-11-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homiy',
            name='tashkilot',
        ),
    ]
