# Generated by Django 3.2.9 on 2021-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_homiy_tashkilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='homiy',
            name='tashkilot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
