# Generated by Django 3.2.9 on 2021-11-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_homiy_sarflangan_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='holati',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiada', 'Moderatsiada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=50),
        ),
        migrations.AlterField(
            model_name='homiy',
            name='turi',
            field=models.CharField(choices=[('Yuridikt', 'Yuridikt'), ('Jismoniy', 'Jismoniy')], max_length=50),
        ),
    ]
