# Generated by Django 3.2.9 on 2021-11-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211111_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('talabalik_turi', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magister', 'Magister')], max_length=50)),
                ('otm', models.CharField(max_length=255)),
                ('kontrakt_summa', models.IntegerField(default=0)),
                ('ajratilgan_summa', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
