# Generated by Django 3.2.9 on 2021-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_homiy_holati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='holati',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiada', 'Moderatsiada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=50),
        ),
    ]
