# Generated by Django 3.2.9 on 2021-11-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_homiy_summa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('personal', models.CharField(choices=[('Juridical', 'Juridical'), ('Physical', 'Physical')], max_length=50)),
                ('phone', models.IntegerField(default=9989)),
                ('amount', models.CharField(choices=[('1 000 000', '1 000 000'), ('5 000 000', '5 000 000'), ('7 000 000', '7 000 000'), ('30 000 000', '30 000 000')], default='1 000 000', max_length=100)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Moderated', 'Moderated'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='New', max_length=50)),
                ('paid', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=50)),
                ('university', models.CharField(max_length=255)),
                ('money_needed', models.IntegerField(default=0)),
                ('money_gained', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Homiy',
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
