# Generated by Django 3.2.9 on 2021-11-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sponsor_my_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.CharField(choices=[('1 000 000', '1 000 000'), ('5 000 000', '5 000 000'), ('7 000 000', '7 000 000'), ('30 000 000', '30 000 000')], default='1 000 000', max_length=100, null=True),
        ),
    ]
