# Generated by Django 3.2.9 on 2021-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_studant_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.CharField(default='1 000 000', max_length=100, null=True),
        ),
    ]
