# Generated by Django 3.2.9 on 2021-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_sponsor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('TTPU', 'Toshkent Turin Politxnika Universiteti'), ('TDSHI', 'Toshkent Davlat Sharqshunoslik Universiteti')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('TTPU', 'Toshkent Turin Politxnika Universiteti'), ('TDSHI', 'Toshkent Davlat Sharqshunoslik Universiteti')], max_length=255),
        ),
    ]
