# Generated by Django 3.2.9 on 2021-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20211113_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=50),
        ),
    ]
