# Generated by Django 3.2.9 on 2021-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='9989', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(default='9989', max_length=100, null=True),
        ),
    ]
