# Generated by Django 3.2.9 on 2021-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_student_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('PAYME', 'Pay me'), ('CLICK', 'Click'), ('ENUMERATION', 'Enumeration')], default='CASH', max_length=100),
        ),
    ]
