# Generated by Django 3.2.9 on 2021-11-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_sponsor_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='personal',
            field=models.CharField(choices=[('Juridical', 'Juridical'), ('Physical', 'Physical')], default='Physical', max_length=50),
        ),
    ]
