# Generated by Django 3.2.9 on 2021-11-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_contracts_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsors',
        ),
    ]
