# Generated by Django 3.2.9 on 2021-11-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_sponsor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.IntegerField(default=1000000, null=True),
        ),
    ]
